version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    # The `env_file` tag allows us to declare an environment file
    env_file:
      - .env # The name of your environment file (the one at the repository root)
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: 123
    #   POSTGRES_DB: nest